### PR TITLE
Add Python 3 compatibility

### PR DESCRIPTION
**Pull request by bngo92**
This requires using avro-python3 instead of avro for Python 3, which has a different API.
Also add tox support.

### CODE REVIEW

**Comment by bngo92** [comment]
@roman-i can you take a look?

**Comment by gth828r** [comment]
+1 on getting this in.  From #2, it sounds like @roman-i was going to poke someone who is still at LinkedIn about getting merge requests in, as he no longer has merge permissions.

**Comment by mhbkb** [comment]
+1 Waiting Python 3 compatibility version.

**Comment by sixninetynine** [comment]
@bngo92 @gth828r @mhbkb sorry for the delays! merged

**Comment by gth828r** [comment]
@sixninetynine no problem, thanks for getting these changes in!

**Pull request merged**
