### PR TITLE
Use fullname

### PR DESCRIPTION
**Pull request by shiraeeshi**
Using fullname makes this serializer more consistent with json serialization of java version of avro.

### CODE REVIEW

**Comment by roman-i** [comment]
thanks for doing this.

I'm not super familiar with name vs fullname, do you want to add a test for this?

I don't have 'merge' permissions anymore. I'll ping somebody from LinkedIn to merge it.

**Comment by shiraeeshi** [comment]
Updated the tests. The fullname is nothing but the name with the namespace prefixed.

**Comment by sixninetynine** [comment]
hey @shiraeeshi sorry it's taken us over a YEAR to address this PR 😞

I'm fine merging this, but would you mind if we bump the version of the library to indicate it's backwards incompatible (from 0.5 to 1.0.0)?

**Comment by jvstein** [comment]
Also waiting on this change. Don't mind if there's a major version change.

**Comment by shiraeeshi** [comment]
@sixninetynine, sorry for taking so long to answer (didn't log in into this account for a long time). No, I don't mind if you change the version.

**Comment by sixninetynine** [comment]
pulled in by #4

**Pull request closed without merging**
